### ISSUE TITLE
Please specify Matrix version with equal separation signs

### ISSUE THREAD

**Issue by tillea** [mojaveazure/seurat-object#145]
Hi,
I'm aware that in R the signs '.' and '-' are sorting equally in version numbers. This is not true for Debian package versions and thus for the latest Debian package I needed the [following patch](https://salsa.debian.org/r-pkg-team/r-cran-seuratobject/-/blob/master/debian/patches/fix_versioning.patch):

    -Imports: future, future.apply, grDevices, grid, Matrix (>= 1.6.1),
    +Imports: future, future.apply, grDevices, grid, Matrix (>= 1.6-1),

for the version of Matrix. It would be extremely helpful if you would simply keep the same spelling for version numbers as the authors of a package have decided for.
Kind regards, Andreas.

**Comment by tillea** [comment]
Hi again,
the new version of seurat-object remains with this unfortunate change of the version of Matrix.  It would be really great if you could change this in your next release.
Thanks a lot, Andreas.

**Comment by mojaveazure** [comment]
Hi Andreas,

Sorry for the delay. I actually don't manage the version of Matrix in `DESCRIPTION` myself, but instead rely on `usethis::use_package()` to handle it for me. For every release of SeuratObject, I have a script that runs
```r
install.packages("Matrix")
usethis::use_package("Matrix", min_version = TRUE)
```
to set the minimum package version of Matrix to the newest version available. As such, it's `usethis` that normalizes the package version to all dots instead of dots and dashes. This is part of an automated release prep I run to keep my burden small. As with Seurat, we (members of @satijalab) only have the bandwitdh to support installations from CRAN and as such, keep these packages compliant with CRAN's standards only. If you know of a way to get `usethis::use_package()` to not normalize package versions to dots (or an alternative to `usethis`, but I would strongly prefer to not change that aspect of my development workflow), I'd be happy to adopt those changes

**Comment by tillea** [comment]
Hi Paul,

Am Wed, Nov 08, 2023 at 01:01:13PM -0800 schrieb Paul Hoffman:
> Sorry for the delay. I actually don't manage the version of Matrix in `DESCRIPTION` myself, but instead rely on `usethis::use_package()` 
> ...
> `usethis` that normalizes the package version to all dots instead of dots and dashes.

OK, understood, that you depend from some tooling.  Thus I adapted our tooling to cope with this.  I admit I will never ever understand why R permits sorting of two different characters same and even has tools to "normalise" what is not normal in IT world outside R.  Thanks for your explanation and woring on seurat, Andreas.

**Comment by eddelbuettel** [comment]
Andreas you have to accept that CRAN is an entity that has the power to set its rules. 

If and when packages _work at CRAN_ in the specified manner but do not in derived work, I have always been of the opinions that this should only us to adapt in the derived use.  I already talked about that in the 'Draft Debian R Policy' that is coming up on its 20 year anniversary (!!) next month, and have done so for all my packages and in all the 'cran to debian' conversions I have worked on.  Asking all upstream maintainers to change packages _that are compliant to the repo they were made for_ always struck me a little as the Ken character in 'A Fish Named Wanda' complaining that everybody in Britain drove on the wrong side of the street ...

**Comment by eddelbuettel** [comment]
(If you consume this by email only only I have a habit of editing comments so maybe see the last version at https://github.com/mojaveazure/seurat-object/issues/145#issuecomment-1805859766 just in case.)
